### PR TITLE
doi infrastructure changes

### PR DESCRIPTION
**Pull request by jukent**

### CODE REVIEW

**Comment by mgrover1** [comment]
@aladinor @gewitterblitz @crystalclearwx can you please add your ORCID IDs and affiliation to this thread?

**Comment by gewitterblitz** [comment]
Sure, here are the details:

ORCID: 0000-0003-3318-7601
Affiliation: Texas A&M University

**Comment by aladinor** [comment]
Sure! 

ORCID: https://orcid.org/0000-0001-8081-7827
Affiliation: University of Illinois at Urbana Champaign

**Comment by crystalclearwx** [comment]
Here you go!
ORCID: https://orcid.org/0009-0009-6628-6287
Affiliation: Problem Solutions, Inc./AccuWeather, Inc.

**Comment by jukent** [comment]
@crystalclearwx do you want your last name as Worley or Camron? 

Everyone check that the info looks good, then we can merge!

**Comment by gewitterblitz** [comment]
Looks good to me!

**Comment by aladinor** [comment]
It looks good to me!

**Comment by crystalclearwx** [comment]
@jukent let's put Camron since it'll be changed soon!

**Pull request merged**
